"""made changes in  baseModel

Revision ID: 588e2778d72c
Revises: b6f93582dd06
Create Date: 2026-05-30 15:45:21.045140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '588e2778d72c'
down_revision: Union[str, Sequence[str], None] = 'b6f93582dd06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('legalcase', 'llm_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('legalcase', 'llm_summary',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
