"""empty message

Revision ID: 5e0ae2e25fba
Revises: e53c00518e44
Create Date: 2026-06-20 07:06:02.812046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0ae2e25fba'
down_revision: Union[str, Sequence[str], None] = 'e53c00518e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legalsection', 'rejection_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legalsection', sa.Column('rejection_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
