"""made minor changes in  baseModel

Revision ID: 615313cc4adc
Revises: 588e2778d72c
Create Date: 2026-05-31 06:38:05.977676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "615313cc4adc"
down_revision: Union[str, Sequence[str], None] = "588e2778d72c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("legalcase", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("legalsection", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "deleted_at")
    op.drop_column("legalsection", "deleted_at")
    op.drop_column("legalcase", "deleted_at")
    # ### end Alembic commands ###
