"""Removed table case_ipc_link

Revision ID: 717ceecc3bd8
Revises: c6ea1a79b238
Create Date: 2026-05-27 08:07:58.857486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '717ceecc3bd8'
down_revision: Union[str, Sequence[str], None] = 'c6ea1a79b238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_ipc_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_ipc_link',
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ipc_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('case_ipc_link_case_id_fkey')),
    sa.ForeignKeyConstraint(['ipc_id'], ['ipc_sections.id'], name=op.f('case_ipc_link_ipc_id_fkey')),
    sa.PrimaryKeyConstraint('case_id', 'ipc_id', name=op.f('case_ipc_link_pkey'))
    )
    # ### end Alembic commands ###
