"""Added Rejection Reason Column 

Revision ID: a745902aeab1
Revises: 5e0ae2e25fba
Create Date: 2026-06-20 07:11:15.296755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a745902aeab1'
down_revision: Union[str, Sequence[str], None] = '5e0ae2e25fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legalsection', sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legalsection', 'rejection_reason')
    # ### end Alembic commands ###
