"""wrote is_deleted in  baseModel

Revision ID: b6f93582dd06
Revises: 5bf4e343d259
Create Date: 2026-05-30 06:34:10.454664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f93582dd06'
down_revision: Union[str, Sequence[str], None] = '5bf4e343d259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legalsection', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_deleted')
    op.drop_column('legalsection', 'is_deleted')
    # ### end Alembic commands ###
