"""Foreign key mapping of cases and IPC sections

Revision ID: c6ea1a79b238
Revises: bc75fbd40d43
Create Date: 2026-05-27 07:49:40.804224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ea1a79b238'
down_revision: Union[str, Sequence[str], None] = 'bc75fbd40d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipc_sections', sa.Column('case_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ipc_sections', 'cases', ['case_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ipc_sections', type_='foreignkey')
    op.drop_column('ipc_sections', 'case_id')
    # ### end Alembic commands ###
