"""add precedent case table

Revision ID: e89212ea6a65
Revises: 615313cc4adc
Create Date: 2026-06-05 21:37:52.261709

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e89212ea6a65'
down_revision: Union[str, Sequence[str], None] = '615313cc4adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precedentcase',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['legalcase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_precedentcase_case_id'), 'precedentcase', ['case_id'], unique=False)
    op.create_index(op.f('ix_precedentcase_id'), 'precedentcase', ['id'], unique=False)
    op.create_index(op.f('ix_precedentcase_is_deleted'), 'precedentcase', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_legalcase_is_deleted'), 'legalcase', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_legalsection_is_deleted'), 'legalsection', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_index(op.f('ix_legalsection_is_deleted'), table_name='legalsection')
    op.drop_index(op.f('ix_legalcase_is_deleted'), table_name='legalcase')
    op.drop_index(op.f('ix_precedentcase_is_deleted'), table_name='precedentcase')
    op.drop_index(op.f('ix_precedentcase_id'), table_name='precedentcase')
    op.drop_index(op.f('ix_precedentcase_case_id'), table_name='precedentcase')
    op.drop_table('precedentcase')
    # ### end Alembic commands ###
