"""add reason and lawyer decision to ipc section

Revision ID: e99f9bc4b8c6
Revises: 3ff599d5e20f
Create Date: 2026-06-07 16:02:50.827982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e99f9bc4b8c6'
down_revision: Union[str, Sequence[str], None] = '3ff599d5e20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'ipc_sections',
    sa.Column('reason', sa.String(), nullable=True)
)
    op.add_column('ipc_sections', sa.Column('lawyer_decision', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ipc_sections', 'lawyer_decision')
    op.drop_column('ipc_sections', 'reason')
    # ### end Alembic commands ###
